info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

spring:
  application:
    name: crtl-adm-server
  profiles:
    active:
      - dev
